<h1 style= 'color:blue', align='center'> Gradient Boosting </h1>

In [1]:
# Import Libraries
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
# Load the data
data = fetch_california_housing()

# Convert into pandas
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [3]:
# Info of the dataset
print("Info of the dataset :\n")
print(df.info())

Info of the dataset :

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   target      20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB
None

In [4]:
# Preprocessing
X = df.drop(columns=['target'])
y = df['target']
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [5]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: target, Length: 20640, dtype: float64

In [6]:
# Split into train_test_split
X_train, X_test,y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [7]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
gb_baseline = GradientBoostingRegressor(random_state=42)
gb_baseline.fit(X_train_scaled,y_train)
y_pred = gb_baseline.predict(X_test_scaled)

In [20]:
# Evaluation
print("\n--- Base line model ---")
print("Mean Absolute Error : ",mean_absolute_error(y_test,y_pred))
print("\n")
print("Mean Squared Error : ",mean_squared_error(y_test,y_pred))
print("\n")
print("R2 score : ",r2_score(y_test,y_pred))

--- Base line model ---
Mean Absolute Error :  0.37165044848436773


Mean Squared Error :  0.29399901242474274


R2 score :  0.7756433164710084

In [10]:
# Hyperparameter tunning
param_grid = {'n_estimators':[100,200], 'learning_rate':[0.1],'max_depth':[3,4]}

In [11]:
random_search = RandomizedSearchCV(
    GradientBoostingRegressor(random_state=42),
    param_distributions=param_grid,
    n_iter=20,  # test 20 random combinations
    cv=5,
    scoring='r2',
    n_jobs=-1,
    verbose=2
)

In [12]:
random_search.fit(X_train_scaled,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 4 is smaller than n_iter=20. Running 4 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=GradientBoostingRegressor(random_state=42),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'learning_rate': [0.1],
                                        'max_depth': [3, 4],
                                        'n_estimators': [100, 200]},
                   scoring='r2', verbose=2)

In [16]:
print("\nBest Parameters found:", random_search.best_params_)
print("Best Cross-Validation R² Score:", random_search.best_score_)

Best Parameters found: {'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.1}
Best Cross-Validation R² Score: 0.8216582245540346

In [18]:
# Train optimised model
gb_best = random_search.best_estimator_
gb_best.fit(X_train_scaled,y_train)
y_pred_best = gb_best.predict(X_test_scaled)

In [19]:
print("\n---- Optimized Model Performance ----")
print("Mean Absolute Error : ",mean_absolute_error(y_test,y_pred_best))
print("\n")
print("Mean Squared Error : ",mean_squared_error(y_test,y_pred_best))
print("\n")
print("R2 score  : ",r2_score(y_test,y_pred_best))

---- Optimized Model Performance ----
Mean Absolute Error :  0.32746655918536927


Mean Squared Error :  0.23782565046511273


R2 score  :  0.8185103624790703

In [23]:
# Performance comparison
print("\n--- Performance comparison ---")
print(f"R2 Before tunning : {r2_score(y_test,y_pred):.3f}")
print(f"R2 After tunning : {r2_score(y_test,y_pred_best):.3f}")

--- Performance comparison ---
R2 Before tunning : 0.776
R2 After tunning : 0.819

In [25]:
single_sample_scaled = X_test_scaled[0].reshape(1,-1)
# Actual prediction
actual_value = y_test.iloc[0]

# Make the prediction
predicted_value = gb_best.predict(single_sample_scaled)[0]

In [27]:
# Single row prediction
print("\n--- Single Row Prediction ---")
print(f"features of the input sample(single): {single_sample_scaled[0]}")
print(f"Actual Median Housing Value : $ {actual_value:.3f}(in millions)")
print(f"Predicted Median Housing Value : $ {predicted_value:.3f}(in millions)")
print(f"Prediction Error : ${abs(actual_value-predicted_value):.3f} millions")

--- Single Row Prediction ---
features of the input sample(single): [-1.15508475 -0.28632369 -0.52068576 -0.17174603 -0.03030109  0.06740798
  0.1951      0.28534728]
Actual Median Housing Value : $ 0.477(in millions)
Predicted Median Housing Value : $ 0.456(in millions)
Prediction Error : $0.021 millions